// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtb88z2mgn9m374SW36Y1Vq95-3rU7XT4',
    appId: '1:169611828835:web:f502c0e59062240c2a2256',
    messagingSenderId: '169611828835',
    projectId: 'stunning-1ee33',
    authDomain: 'stunning-1ee33.firebaseapp.com',
    storageBucket: 'stunning-1ee33.appspot.com',
    measurementId: 'G-N8DMLCVX6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAySS-qn97wVUtxR98bztB4y74P_dVts3Q',
    appId: '1:169611828835:android:35e5d497da0d80ff2a2256',
    messagingSenderId: '169611828835',
    projectId: 'stunning-1ee33',
    storageBucket: 'stunning-1ee33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjAzzY18-BTIV4ir2EKody1kpL5lv-lMc',
    appId: '1:169611828835:ios:984864830783456b2a2256',
    messagingSenderId: '169611828835',
    projectId: 'stunning-1ee33',
    storageBucket: 'stunning-1ee33.appspot.com',
    iosClientId: '169611828835-d9n291337d1jrrtci6hhdkdp85dt847d.apps.googleusercontent.com',
    iosBundleId: 'com.example.stunning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjAzzY18-BTIV4ir2EKody1kpL5lv-lMc',
    appId: '1:169611828835:ios:920c771530f4b02b2a2256',
    messagingSenderId: '169611828835',
    projectId: 'stunning-1ee33',
    storageBucket: 'stunning-1ee33.appspot.com',
    iosClientId: '169611828835-g66ki5belc5kvit9cl6n9i3e44j1r2v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.stunning.RunnerTests',
  );
}
